export const APPLICATION_REQUEST = "APPLICATION_REQUEST";
export const APPLICATION_SECCESS = "APPLICATION_SECCESS";
export const APPLICATION_FAIL = "APPLICATION_FAIL";
export const APPLICATION_RESET = "APPLICATION_RESET";

export const ALL_APPLICATIONS_REQUEST = "ALL_APPLICATIONS_REQUEST";
export const ALL_APPLICATIONS_SECCESS = "ALL_APPLICATIONS_SECCESS";
export const ALL_APPLICATIONS_FAIL = "ALL_APPLICATIONS_FAIL";

export const DELETE_APPLICATIONS_RESET = "DELETE_APPLICATIONS_RESET";
export const DELETE_APPLICATIONS_SUCCESS = "DELETE_APPLICATIONS_SUCCESS";
export const DELETE_APPLICATIONS_REQUEST = "DELETE_APPLICATIONS_REQUEST";
export const DELETE_APPLICATIONS_FAIL = "DELETE_APPLICATIONS_FAIL";

export const UPDATE_APPLICATIONS_RESET = "UPDATE_APPLICATIONS_RESET";
export const UPDATE_APPLICATIONS_SUCCESS = "UPDATE_APPLICATIONS_SUCCESS";
export const UPDATE_APPLICATIONS_REQUEST = "UPDATE_APPLICATIONS_REQUEST";
export const UPDATE_APPLICATIONS_FAIL = "UPDATE_APPLICATIONS_FAIL";

export const APPLICATIONS_DETAILS_REQUEST = "APPLICATIONS_DETAILS_REQUEST";
export const APPLICATIONS_DETAILS_SUCCESS = "APPLICATIONS_DETAILS_SUCCESS";
export const APPLICATIONS_DETAILS_FAIL = "APPLICATIONS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";